### ISSUE TITLE
error when trying to run example

### ISSUE THREAD

**Issue by sbluatx** [highwall/pexpect-serial#11]
>>> import serial
>>> from pexpect_serial import SerialSpawn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python36\lib\site-packages\pexpect_serial\__init__.py", line 1, in <module>
    from .serial_spawn import SerialSpawn
  File "C:\python36\lib\site-packages\pexpect_serial\serial_spawn.py", line 24, in <module>
    from pexpect import spawn
ImportError: cannot import name 'spawn'
>>>

**Comment by sbluatx** [comment]
seems like from [https://pexpect.readthedocs.io/en/stable/overview.html#windows](url) pexpect.spawn is not available on windows
>>> pexpect.__version__
'4.8.0'

**Comment by david-drinn** [comment]
For my use case, I was using `pexpect-serial` on Windows for years. ~~I'm not sure what changed in `pexpect` that removed that support. I'm guessing someone realized a technicality that is important for some use cases but not others, and removed support.~~ 

~~Looking to see which version of pexpect was used before where this worked.~~

EDIT: My guess that `pexpect` broke this was wrong.  See below.

**Comment by david-drinn** [comment]
`pip install --force-reinstall -v "pexpect_serial==0.0.4"` resolved this issue for me. That is, use version 0.0.4 of `pexpect_serial`, not 0.1.0.

**Comment by david-drinn** [comment]
4488ae405bb27e6c7686e0dfa9f5453737a12dc2 appears to be the culprit commit that broke this in `pexpect_serial`.

**Comment by dancollins** [comment]
Running `pip install pexpect-serial==0.0.4` on windows fixed it for me, too. Running Windows 11, miniconda and Python 3.11.

**Comment by david-drinn** [comment]
I found some other odd behavior introduced in 0.1.0.

For my use case, I was expecting 552 bytes of data. I received it, but upon inspection, the last 512 bytes should be zeroes. I can confirm as much with a logic analyzer and debugger on the device end. And at 0.0.4 I do indeed get that. 

However, at 0.1.0 some data in the middle is inserting some data somehow. It's the same data consistent across multiple devices and multiple laptops.

0.1.0 should be reverted.
