### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by wsliou** [highwall/pexpect-serial#8]
Hello
I run below code but got TypeError
`import serial
from pexpect_serial import SerialSpawn

with serial.Serial('/dev/ttyUSB0', 115200, timeout=0) as ser:
    ss = SerialSpawn(ser)
    ss.sendline('start')
    ss.expect('done')`

console show
Traceback (most recent call last):
  File "serial_test2.py", line 5, in <module>
    ss = SerialSpawn(ser)
  File "/usr/local/lib/python2.7/dist-packages/pexpect_serial/serial_spawn.py", line 41, in __init__
    super().__init__(None, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

OS Ubuntu 16.04 64bit
Python 2.7.12

Any idea?

**Comment by bamartin125** [comment]
That form of `super()` is a Python3 only usage. My guess is that pexpect-serial is not python2 compatible.

**Comment by kelvinyu** [comment]
see https://github.com/btbroot/pexpect-serial/commit/c8770a3e107ca1ed0fac78d36660a7f89316afcf
